<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="cdpr" xmlns:xacro="http://www.ros.org/wiki/xacro">


<!-- Ce code permet de générer le cadre du robot, les liaisons entre les parties du cadre et la plateforme-->
<!-- Bien faire gaffe à repercuter les valeurs des paramètres changés ici sur cube1.yaml-->

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931" />
  <xacro:property name="cable_mass" value="0.001" />
  <xacro:property name="cable_radius" value="0.001" />
  <xacro:property name="frame_color" value="orange" /> <!-- les couleurs ne fonctionnent pas en fait, que sur urdf viewer -->
  <xacro:property name="frame_lower" value="1.0 1.0 0" />
  <xacro:property name="frame_radius" value="0.02" />
  <xacro:property name="frame_lenght" value="2" />
  <xacro:property name="frame_type" value="box" />

  <xacro:property name="cable_color" value="blue" />

  <xacro:property name="platform_size" value="0.3" />
  <xacro:property name="platform_color" value="red" />
  <xacro:property name="platform_pos_x" value="0.3" />
  <xacro:property name="platform_pos_y" value="0.3" />
  <xacro:property name="platform_pos_z" value="0.5" />
  <xacro:property name="platform_pos_rpy" value="0" />
  <xacro:property name="platform_mass" value="5" />
  <xacro:property name="platform_iaa" value="0.33" /> <!-- ixx iyy izz-->
  <xacro:property name="platform_iab" value="0" />

  <!-- Import all Gazebo-customization elements, including Gazebo colors(au cas ca marcherait un jour) -->
 <xacro:include filename="$(find cdpr)/urdf/cube.gazebo" /> 
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find cdpr)/urdf/materials.xacro" />
  <xacro:include filename="$(find cdpr)/urdf/cube1.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->

  <link name="world" /> 

  <joint name="fixed" type="fixed">
    <parent link="world" />
    <child link="frame_1" />
  </joint>

  <!-- le float n'existe pas en sdf et cette liaison sera transformée en fixed dans gazebo -->
  <!-- Il faut trouver une solution pour le rendre mobile en selectionnant un jeu de liaison qui le lie à world -->


  <joint name="float_platform" type="floating"> 
    <parent link="world" />
    <child link="platform" />
  </joint>

<!-- 


  <link name="virt_Xl">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<mass value="0.001"/>
			<inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
		</inertial>
	</link>

  <joint name="prism_1" type="prismatic">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="virt_X1" />
    <child link="platform" />
    <limit lower="-2" upper="2" effort="10000" velocity="1"/>
    <axis xyz="1 0 0"/>
  </joint>

  <link name="virt_Yl">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<mass value="0.001"/>
			<inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
		</inertial>
	</link>

  <joint name="prism2" type="prismatic">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="virt_X1" />
    <child link="virt_Y1" />
    <limit lower="-2" upper="2" effort="10000" velocity="1"/>
    <axis xyz="1 0 0"/>
  </joint>

  <joint name="prism3" type="prismatic">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="world" />
    <child link="virt_Y1" />
    <limit lower="-2" upper="2" effort="10000" velocity="1"/>
    <axis xyz="0 0 1"/>
  </joint>

-->

  <!-- Base Link -->

  <link name="frame_1">
    <collision>
      <origin xyz="${-frame_lenght/2} ${-frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="${-frame_lenght/2} ${-frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
      <material name="${frame_color}" />
    </visual>
    <inertial>
      <origin xyz="${-frame_lenght/2} ${-frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0" />
      <mass value="10000" />
      <inertia ixx="10000" ixy="0.0" ixz="0.0" iyy="10000" iyz="0.0" izz="10000" />
    </inertial>
  </link>

  <link name="frame_2">
    <collision>
      <origin xyz="${-frame_lenght/2} 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="${-frame_lenght/2} 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
      <material name="${frame_color}" />
    </visual>
    <inertial>
      <origin xyz="${-frame_lenght/2} 0 0" rpy="${PI/2} 0 0" />
      <mass value="10000" />
      <inertia ixx="10000" ixy="0.0" ixz="0.0" iyy="10000" iyz="0.0" izz="10000" />
    </inertial>
  </link>

  <link name="frame_3">
    <collision>
      <origin xyz="0 ${-frame_lenght/2} 0" rpy="0 ${PI/2} 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 ${-frame_lenght/2} 0" rpy="0 ${PI/2} 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
      <material name="${frame_color}" />
    </visual>
    <inertial>
      <origin xyz="0 ${-frame_lenght/2} 0" rpy="0 ${PI/2} 0" />
      <mass value="10000" />
      <inertia ixx="10000" ixy="0.0" ixz="0.0" iyy="10000" iyz="0.0" izz="10000" />
    </inertial>
  </link>

  <link name="frame_4">
    <collision>
      <origin xyz="${-frame_lenght/2} ${frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="${-frame_lenght/2} ${frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
      <material name="${frame_color}" />
    </visual>
    <inertial>
      <origin xyz="${-frame_lenght/2} ${frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0" />
      <mass value="10000" />
      <inertia ixx="10000" ixy="0.0" ixz="0.0" iyy="10000" iyz="0.0" izz="10000" />
    </inertial>
  </link>

  <link name="frame_5">
    <collision>
      <origin xyz="${frame_lenght/2} ${frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="${frame_lenght/2} ${frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
      <material name="${frame_color}" />
    </visual>
    <inertial>
      <origin xyz="${frame_lenght/2} ${frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0" />
      <mass value="10000" />
      <inertia ixx="10000" ixy="0.0" ixz="0.0" iyy="10000" iyz="0.0" izz="10000" />
    </inertial>
  </link>

  <link name="frame_6">
    <collision>
      <origin xyz="${frame_lenght/2} ${-frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="${frame_lenght/2} ${-frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
      <material name="${frame_color}" />
    </visual>
    <inertial>
      <origin xyz="${frame_lenght/2} ${-frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0" />
      <mass value="10000" />
      <inertia ixx="10000" ixy="0.0" ixz="0.0" iyy="10000" iyz="0.0" izz="10000" />
    </inertial>
  </link>

  <link name="frame_7">
    <collision>
      <origin xyz="0 ${frame_lenght/2} 0" rpy="0 ${-PI/2} 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 ${frame_lenght/2} 0" rpy="0 ${-PI/2} 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
      <material name="${frame_color}" />
    </visual>
    <inertial>
      <origin xyz="0 ${frame_lenght/2} ${frame_lenght/2}" rpy="0 ${-PI/2} 0" />
      <mass value="10000" />
      <inertia ixx="10000" ixy="0.0" ixz="0.0" iyy="10000" iyz="0.0" izz="10000" />
    </inertial>
  </link>

  <link name="frame_8">
    <collision>
      <origin xyz="${frame_lenght/2} 0 0" rpy="0 ${-PI/2} 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="${frame_lenght/2} 0 0" rpy="${-PI/2} 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
      <material name="${frame_color}" />
    </visual>
    <inertial>
      <origin xyz="${frame_lenght/2} 0 0" rpy="0 ${-PI/2} 0" />
      <mass value="10000" />
      <inertia ixx="10000" ixy="0.0" ixz="0.0" iyy="10000" iyz="0.0" izz="10000" />
    </inertial>
  </link>

  <link name="frame_9">
    <collision>
      <origin xyz="${frame_lenght/2} 0 ${frame_lenght}" rpy="0 ${-PI/2} 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="${frame_lenght/2} 0 ${frame_lenght}" rpy="${-PI/2} 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
      <material name="${frame_color}" />
    </visual>
    <inertial>
      <origin xyz="${frame_lenght/2} 0 ${frame_lenght}" rpy="0 ${-PI/2} 0" />
      <mass value="10000" />
      <inertia ixx="10000" ixy="0.0" ixz="0.0" iyy="10000" iyz="0.0" izz="10000" />
    </inertial>
  </link>

  <link name="frame_10">
    <collision>
      <origin xyz="0 ${frame_lenght/2} ${frame_lenght}" rpy="0 ${-PI/2} 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 ${frame_lenght/2} ${frame_lenght}" rpy="0 ${-PI/2} 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
      <material name="${frame_color}" />
    </visual>
    <inertial>
      <origin xyz="0 ${frame_lenght/2} ${frame_lenght}" rpy="0 ${-PI/2} 0" />
      <mass value="10000" />
      <inertia ixx="10000" ixy="0.0" ixz="0.0" iyy="10000" iyz="0.0" izz="10000" />
    </inertial>
  </link>


  <link name="frame_11">
    <collision>
      <origin xyz="${-frame_lenght/2} 0 ${frame_lenght}" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="${-frame_lenght/2} 0 ${frame_lenght}" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
      <material name="${frame_color}" />
    </visual>
    <inertial>
      <origin xyz="${-frame_lenght/2} 0 ${frame_lenght}" rpy="${PI/2} 0 0" />
      <mass value="10000" />
      <inertia ixx="10000" ixy="0.0" ixz="0.0" iyy="10000" iyz="0.0" izz="10000" />
    </inertial>
  </link>

  <link name="frame_12">
    <collision>
      <origin xyz="0 ${-frame_lenght/2} ${frame_lenght}" rpy="0 ${PI/2} 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 ${-frame_lenght/2} ${frame_lenght}" rpy="0 ${PI/2} 0" />
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}" />
      </geometry>
      <material name="${frame_color}" />
    </visual>
    <inertial>
      <origin xyz="0 ${-frame_lenght/2} ${frame_lenght}" rpy="0 ${PI/2} 0" />
      <mass value="10000" />
      <inertia ixx="10000" ixy="0.0" ixz="0.0" iyy="10000" iyz="0.0" izz="10000" />
    </inertial>
  </link>

  <link name="platform">
    <collision>
      <origin xyz="${platform_pos_x} ${platform_pos_y} ${platform_pos_z}" rpy="${platform_pos_rpy} ${platform_pos_rpy} ${platform_pos_rpy}" />
      <geometry>
        <box size="${platform_size} ${platform_size} ${platform_size}" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="${platform_pos_x} ${platform_pos_y} ${platform_pos_z}" rpy="${platform_pos_rpy} ${platform_pos_rpy} ${platform_pos_rpy}" />
      <geometry>
        <box size="${platform_size} ${platform_size} ${platform_size}" />
      </geometry>
      <material name="${platform_color}" />
    </visual>
    <inertial>
      <origin xyz="${platform_pos_x} ${platform_pos_y} ${platform_pos_z}" rpy="${platform_pos_rpy} ${platform_pos_rpy} ${platform_pos_rpy}" />
      <mass value="${platform_mass}" />
      <inertia ixx="${platform_iaa}" ixy="${platform_iab}" ixz="${platform_iab}" iyy="${platform_iaa}" iyz="${platform_iab}" izz="${platform_iaa}" />
    </inertial>
  </link>

<xacro:macro name="default_joint" params="num1 num2"> <!-- définit une macro de liaison entre les parties du cube -->
  <joint name="fixed${num1}" type="fixed">
    <parent link="frame_${num2}" />
    <child link="frame_${num1}" />
  </joint>
</xacro:macro>

<xacro:macro name="loop" params="links_qty"> <!-- permet d'executer la macro en boucle -->
  <xacro:default_joint num1="${links_qty+2}" num2="${links_qty+1}"/>
    <xacro:if value="${links_qty}">
        <xacro:loop links_qty="${links_qty-1}" />
    </xacro:if>
</xacro:macro>

<!-- Ne sert plus mais permettait de fixer les cables au cadre pour tester les liaisons -->
<xacro:macro name="default_joint_cable" params="num1"> 
  <joint name="cable_fixed${num1}" type="floating">
    <parent link="frame_1" />
    <child link="cable${num1-1}" />
  </joint>
</xacro:macro>

<xacro:macro name="loop2" params="links_qty">
  <xacro:default_joint_cable num1="${links_qty+1}" />
    <xacro:if value="${links_qty}">
        <xacro:loop2 links_qty="${links_qty-1}" />
    </xacro:if>
</xacro:macro>

<xacro:loop links_qty="10" /> <!-- execute la macro -->

<!-- <xacro:loop2 links_qty="7" /> -->

</robot>